In [1]:
import pandas as pd
import numpy as np
import gc

In [2]:
df2 = pd.read_csv('../bus_data/stationmap/location_merge_near.csv')
df1 = pd.read_csv('../bus_data/stationmap/train_amap_correct.csv')

In [3]:
df1

O_LINENO  O_UP  STATION  O_LONGITUDE  O_LATITUDE  longitude_amap  \
0             1     0        1      117.198     39.1274      117.204307   
1             1     0        2      117.199     39.1258      117.205306   
2             1     0        3      117.195     39.1224      117.201312   
3             1     0        4      117.192     39.1207      117.198317   
4             1     0        5      117.187     39.1229      117.193325   
5             1     0        6      117.178     39.1252      117.184342   
6             1     0        7      117.179     39.1288      117.185341   
7             1     0        8      117.183     39.1293      117.189334   
8             1     0        9      117.186     39.1327      117.192329   
9             1     0       10      117.186     39.1347      117.192329   
10            1     0       11      117.181     39.1359      117.187338   
11            1     0       12      117.180     39.1394      117.186341   
12            1     0       13      117.180     39.1422      117.186341   
13            1     0       14      117.182     39.1431      117.188337   
14            1     0       15      117.189     39.1517      117.195326   
15            1     0       16      117.192     39.1555      117.198321   
16            1     0       17      117.194     39.1574      117.200318   
17            1     0       18      117.197     39.1593      117.203313   
18            1     0       19      117.200     39.1628      117.206309   
19            1     0       20      117.211     39.1650      117.217294   
20            1     0       21      117.214     39.1650      117.220291   
21            1     0       22      117.218     39.1653      117.224287   
22            1     0       23      117.220     39.1670      117.226285   
23            1     0       24      117.216     39.1699      117.222289   
24            1     0       25      117.218     39.1729      117.224287   
25            1     0       26      117.221     39.1743      117.227285   
26            1     0       27      117.225     39.1766      117.231282   
27            1     0       28      117.229     39.1774      117.235280   
28            1     0       29      117.231     39.1750      117.237279   
29            1     0       30      117.233     39.1729      117.239278   
...         ...   ...      ...          ...         ...             ...   
22343     61102     1       21      117.102     39.2688      117.108448   
22344     61102     1       22      117.104     39.2629      117.110448   
22345     61102     1       23      117.105     39.2587      117.111448   
22346     61102     1       24      117.108     39.2544      117.114448   
22347     61102     1       25      117.117     39.2340      117.123443   
22348     61102     1       26      117.119     39.2286      117.125442   
22349     61102     1       27      117.121     39.2240      117.127440   
22350     61102     1       28      117.128     39.2176      117.134434   
22351     61102     1       29      117.131     39.2140      117.137431   
22352     61102     1       30      117.134     39.2103      117.140427   
22353     61102     1       31      117.143     39.1995      117.149414   
22354     61102     1       32      117.150     39.1934      117.156402   
22355     61102     1       33      117.157     39.1881      117.163389   
22356     61102     1       34      117.160     39.1858      117.166384   
22357     61102     1       35      117.169     39.1818      117.175366   
22358     61102     1       36      117.174     39.1751      117.180356   
22359     61102     1       37      117.176     39.1714      117.182352   
22360     61102     1       38      117.178     39.1692      117.184348   
22361     61102     1       39      117.180     39.1651      117.186344   
22362     61102     1       40      117.184     39.1601      117.190336   
22363     61102     1       41      117.186     39.1576      117.192332   
22364     61102     1       42  

In [4]:
df2

station_id            name   longitude   latitude
0              0           247社区  117.337807  39.709927
1              1           奥克斯电气  117.010269  39.416382
2              2             奥兰里  117.252777  39.133121
3              3         奥林匹克博物馆  117.554939  38.927555
4              4            奥林花园  117.654144  39.044552
5              5             安乐村  117.362724  39.689865
6              6            安光小学  116.999702  39.217419
7              7             安光村  116.999611  39.223274
8              8           安光油墨厂  116.999649  39.221779
9              9             安太里  117.655975  39.017632
10            10             安定里  117.186646  39.165951
11            11             安泽里  117.136047  39.145187
12            12            安津医院  117.069290  39.233574
13            13            安裕新村  117.418961  40.039059
14            14             安达桥  117.424843  38.871178
15            15             安阳道  117.663864  38.993320
16            16           敖北/敖西  116.930908  39.308361
17            17            敖嘴村口  116.958267  39.312737
18            18            爱国东里  117.394356  38.670040
19            19            爱国北里  117.218575  39.098717
20            20             爱国里  117.220016  39.097752
21            21             爱营里  117.249550  39.146576
22            22             艾林庄  117.643242  39.455292
23            23             艾蒲庄  116.997688  39.319023
24            24            阿尔卑斯  117.235428  38.993500
25            25            鞍山西道  117.157745  39.113945
26            26             鞍山道  117.188660  39.120312
27            27           BBA公司  117.713768  39.051575
28            28            五号堤路  117.223724  39.074368
29            29            保利天汇  117.812114  39.338536
...          ...             ...         ...        ...
5396        5396              赵庄  117.197662  39.258694
5397        5397            赵庄中学  117.804924  39.353687
5398        5398             赵庄南  112.536469  37.922756
5399        5399             赵庄子  116.239403  40.060726
5400        5400            赵庄子村  116.832458  38.875572
5401        5401              赵本  117.652069  39.467297
5402        5402             赵沽里  117.249886  39.170387
5403        5403             赵温村  117.407166  39.253456
5404        5404           赵翰林庄村  117.248566  39.954449
5405        5405            赵苑小区  117.110329  39.153313
5406        5406             赵连庄  117.235802  38.794861
5407        5407          辰兴路佳宁道  117.132523  39.197834
5408        5408            造甲中学  117.454544  39.282444
5409        5409         造甲国道服务站  117.407872  39.292724
5410        5410           造甲工业区  117.437706  39.282700
5411        5411           造甲邮政所  117.451912  39.282478
5412        5412           造甲镇政府  117.431793  39.282909
5413        5413  造纸宿舍/造纸宿舍(张贵庄)  117.310730  39.091541
5414        5414             郑家套  117.402817  39.932892
5415        5415             郑家楼  116.887917  39.192200
5416        5416             郑州道  117.811913  38.999084
5417        5417             郑庄子  117.252625  39.091072
5418        5418        郑庄子[西青区]  116.984329  39.098854
5419        5419            郑庄子村  117.545265  39.002903
5420        5420              重工  117.728271  38.982819
5421        5421           重阳里南门  117.463348  38.844570
5422        5422            鑫银大厦  117.203323  39.096134
5423        5423            钻井公司  117.513802  38.691814
5424        5424        镇政府[静海镇]  116.922920  38.929836
5425        5425             震新村  117.809563  39.278263

[5426 rows x 4 columns]

In [5]:
a_x = np.ones((len(df2),len(df1)))
a_x.shape

(5426, 22373)

In [6]:
ttt = np.array(df1.longitude_amap)
ttt

array([117.20430745, 117.20530572, 117.20131185, ..., 117.19033149,
       117.20031331, 117.20330811])

In [7]:
a_x = ttt * a_x
a_x = a_x.T
a_x

array([[117.20430745, 117.20430745, 117.20430745, ..., 117.20430745,
        117.20430745, 117.20430745],
       [117.20530572, 117.20530572, 117.20530572, ..., 117.20530572,
        117.20530572, 117.20530572],
       [117.20131185, 117.20131185, 117.20131185, ..., 117.20131185,
        117.20131185, 117.20131185],
       ...,
       [117.19033149, 117.19033149, 117.19033149, ..., 117.19033149,
        117.19033149, 117.19033149],
       [117.20031331, 117.20031331, 117.20031331, ..., 117.20031331,
        117.20031331, 117.20031331],
       [117.20330811, 117.20330811, 117.20330811, ..., 117.20330811,
        117.20330811, 117.20330811]])

In [8]:
b_x = np.ones((len(df1),len(df2)))
ttt = np.array(df2.longitude)
b_x = ttt * b_x
b_x

array([[117.337807, 117.010269, 117.252777, ..., 117.513802, 116.92292 ,
        117.809563],
       [117.337807, 117.010269, 117.252777, ..., 117.513802, 116.92292 ,
        117.809563],
       [117.337807, 117.010269, 117.252777, ..., 117.513802, 116.92292 ,
        117.809563],
       ...,
       [117.337807, 117.010269, 117.252777, ..., 117.513802, 116.92292 ,
        117.809563],
       [117.337807, 117.010269, 117.252777, ..., 117.513802, 116.92292 ,
        117.809563],
       [117.337807, 117.010269, 117.252777, ..., 117.513802, 116.92292 ,
        117.809563]])

## 计算y差值

In [9]:
a_y = np.ones((len(df2),len(df1)))
ttt = np.array(df1.latitude_amap)

In [10]:
a_y = a_y * ttt
a_y = a_y.T
a_y

array([[39.12843669, 39.12843669, 39.12843669, ..., 39.12843669,
        39.12843669, 39.12843669],
       [39.12683431, 39.12683431, 39.12683431, ..., 39.12683431,
        39.12683431, 39.12683431],
       [39.12343859, 39.12343859, 39.12343859, ..., 39.12343859,
        39.12343859, 39.12343859],
       ...,
       [39.12776042, 39.12776042, 39.12776042, ..., 39.12776042,
        39.12776042, 39.12776042],
       [39.12354031, 39.12354031, 39.12354031, ..., 39.12354031,
        39.12354031, 39.12354031],
       [39.12223443, 39.12223443, 39.12223443, ..., 39.12223443,
        39.12223443, 39.12223443]])

In [11]:
b_y = np.ones((len(df1),len(df2)))
ttt = np.array(df2.latitude)

In [12]:
b_y = ttt * b_y
b_y

array([[39.709927, 39.416382, 39.133121, ..., 38.691814, 38.929836,
        39.278263],
       [39.709927, 39.416382, 39.133121, ..., 38.691814, 38.929836,
        39.278263],
       [39.709927, 39.416382, 39.133121, ..., 38.691814, 38.929836,
        39.278263],
       ...,
       [39.709927, 39.416382, 39.133121, ..., 38.691814, 38.929836,
        39.278263],
       [39.709927, 39.416382, 39.133121, ..., 38.691814, 38.929836,
        39.278263],
       [39.709927, 39.416382, 39.133121, ..., 38.691814, 38.929836,
        39.278263]])

In [14]:
distance = (a_x*1000 - b_x*1000)**2 + (a_y*1000 - b_y*1000)**2
distance

array([[355953.11371348, 120563.42553734,   2371.23964375, ...,
        286426.24384157, 118621.13206779, 388782.19975312],
       [357553.67490062, 121877.18633603,   2293.04505719, ...,
        284412.62583487, 118550.02801072, 388057.51065473],
       [362599.58710481, 122313.21448923,   2742.41093055, ...,
        283949.87693447, 114983.9825126 , 393940.06220108],
       ...,
       [360666.9571781 , 115724.91820824,   3928.17773319, ...,
        294682.44987513, 110682.97901028, 406098.69215696],
       [362753.86356618, 121873.09641764,   2844.22798393, ...,
        284662.76340467, 114468.41038303, 395124.29082983],
       [363472.51034011, 123786.88961604,   2565.68894873, ...,
        281668.20446023, 115634.6452679 , 391889.91203181]])

In [15]:
del [a_x,a_y,b_x,b_y]
gc.collect()

0

## 保存数据

In [16]:
np.save('match.npy',distance)

## 读取数据

In [5]:
distance = np.load('match.npy')
distance

array([[355953.11371348, 120563.42553734,   2371.23964375, ...,
        262950.37369908, 118621.1320678 , 388782.19975312],
       [357553.67490063, 121877.18633603,   2293.04505719, ...,
        261483.84490923, 118550.02801073, 388057.51065473],
       [362599.58710482, 122313.21448923,   2742.41093055, ...,
        264375.18283021, 114983.98251261, 393940.06220108],
       ...,
       [360666.95717811, 115724.91820824,   3928.17773319, ...,
        276609.49352055, 110682.97901028, 406098.69215696],
       [362753.86356619, 121873.09641764,   2844.22798393, ...,
        265389.28151735, 114468.41038304, 395124.29082983],
       [363472.51034011, 123786.88961604,   2565.68894873, ...,
        262057.00091929, 115634.64526791, 391889.91203181]])

In [17]:
aaa = []
for i in range(distance.shape[0]):
#for i in range(1000):
    ttt = np.where(distance[i,:] == distance[i,:].min())
    realid = ttt[0][0]
    a = df2[df2.station_id == realid]
    aaa.append(a.index[0])
aaa

[233,
 233,
 3504,
 248,
 1612,
 31,
 3303,
 309,
 4214,
 4215,
 3532,
 1465,
 360,
 89,
 2306,
 1950,
 5252,
 527,
 131,
 102,
 133,
 3836,
 3836,
 1346,
 3580,
 2092,
 410,
 411,
 3339,
 2393,
 2393,
 2393,
 3339,
 411,
 410,
 2092,
 3580,
 1346,
 2093,
 3836,
 133,
 102,
 131,
 528,
 5252,
 1950,
 2306,
 89,
 360,
 1465,
 3532,
 4215,
 309,
 3319,
 3980,
 1613,
 249,
 3505,
 233,
 1201,
 3816,
 944,
 4351,
 1817,
 549,
 250,
 26,
 2006,
 2922,
 2891,
 2369,
 1263,
 546,
 5256,
 4609,
 2780,
 4486,
 2140,
 5101,
 1185,
 136,
 2204,
 2319,
 757,
 5030,
 757,
 2319,
 2204,
 2204,
 1185,
 5101,
 4236,
 2139,
 4609,
 4253,
 546,
 1263,
 2369,
 2891,
 2922,
 2006,
 1728,
 26,
 250,
 549,
 1817,
 4351,
 944,
 3816,
 3846,
 879,
 103,
 4214,
 4215,
 3532,
 1465,
 360,
 151,
 1253,
 3346,
 4557,
 4624,
 572,
 4624,
 4557,
 3346,
 151,
 360,
 1465,
 3532,
 4215,
 4843,
 3679,
 214,
 3680,
 215,
 1838,
 503,
 3768,
 3021,
 53,
 53,
 2487,
 4407,
 1382,
 43,
 771,
 4843,
 3846,
 3633,
 3033,
 4

In [18]:
result = df1.copy()
result['station_id'] = aaa
result

O_LINENO  O_UP  STATION  O_LONGITUDE  O_LATITUDE  longitude_amap  \
0             1     0        1      117.198     39.1274      117.204307   
1             1     0        2      117.199     39.1258      117.205306   
2             1     0        3      117.195     39.1224      117.201312   
3             1     0        4      117.192     39.1207      117.198317   
4             1     0        5      117.187     39.1229      117.193325   
5             1     0        6      117.178     39.1252      117.184342   
6             1     0        7      117.179     39.1288      117.185341   
7             1     0        8      117.183     39.1293      117.189334   
8             1     0        9      117.186     39.1327      117.192329   
9             1     0       10      117.186     39.1347      117.192329   
10            1     0       11      117.181     39.1359      117.187338   
11            1     0       12      117.180     39.1394      117.186341   
12            1     0       13      117.180     39.1422      117.186341   
13            1     0       14      117.182     39.1431      117.188337   
14            1     0       15      117.189     39.1517      117.195326   
15            1     0       16      117.192     39.1555      117.198321   
16            1     0       17      117.194     39.1574      117.200318   
17            1     0       18      117.197     39.1593      117.203313   
18            1     0       19      117.200     39.1628      117.206309   
19            1     0       20      117.211     39.1650      117.217294   
20            1     0       21      117.214     39.1650      117.220291   
21            1     0       22      117.218     39.1653      117.224287   
22            1     0       23      117.220     39.1670      117.226285   
23            1     0       24      117.216     39.1699      117.222289   
24            1     0       25      117.218     39.1729      117.224287   
25            1     0       26      117.221     39.1743      117.227285   
26            1     0       27      117.225     39.1766      117.231282   
27            1     0       28      117.229     39.1774      117.235280   
28            1     0       29      117.231     39.1750      117.237279   
29            1     0       30      117.233     39.1729      117.239278   
...         ...   ...      ...          ...         ...             ...   
22343     61102     1       21      117.102     39.2688      117.108448   
22344     61102     1       22      117.104     39.2629      117.110448   
22345     61102     1       23      117.105     39.2587      117.111448   
22346     61102     1       24      117.108     39.2544      117.114448   
22347     61102     1       25      117.117     39.2340      117.123443   
22348     61102     1       26      117.119     39.2286      117.125442   
22349     61102     1       27      117.121     39.2240      117.127440   
22350     61102     1       28      117.128     39.2176      117.134434   
22351     61102     1       29      117.131     39.2140      117.137431   
22352     61102     1       30      117.134     39.2103      117.140427   
22353     61102     1       31      117.143     39.1995      117.149414   
22354     61102     1       32      117.150     39.1934      117.156402   
22355     61102     1       33      117.157     39.1881      117.163389   
22356     61102     1       34      117.160     39.1858      117.166384   
22357     61102     1       35      117.169     39.1818      117.175366   
22358     61102     1       36      117.174     39.1751      117.180356   
22359     61102     1       37      117.176     39.1714      117.182352   
22360     61102     1       38      117.178     39.1692      117.184348   
22361     61102     1       39      117.180     39.1651      117.186344   
22362     61102     1       40      117.184     39.1601      117.190336   
22363     61102     1       41      117.186     39.1576      117.192332   
22364     61102     1       42  

In [19]:
result = pd.merge(left=result,right=df2,left_on=['station_id'],right_on=['station_id'],how='left')
result

O_LINENO  O_UP  STATION  O_LONGITUDE  O_LATITUDE  longitude_amap  \
0             1     0        1      117.198     39.1274      117.204307   
1             1     0        2      117.199     39.1258      117.205306   
2             1     0        3      117.195     39.1224      117.201312   
3             1     0        4      117.192     39.1207      117.198317   
4             1     0        5      117.187     39.1229      117.193325   
5             1     0        6      117.178     39.1252      117.184342   
6             1     0        7      117.179     39.1288      117.185341   
7             1     0        8      117.183     39.1293      117.189334   
8             1     0        9      117.186     39.1327      117.192329   
9             1     0       10      117.186     39.1347      117.192329   
10            1     0       11      117.181     39.1359      117.187338   
11            1     0       12      117.180     39.1394      117.186341   
12            1     0       13      117.180     39.1422      117.186341   
13            1     0       14      117.182     39.1431      117.188337   
14            1     0       15      117.189     39.1517      117.195326   
15            1     0       16      117.192     39.1555      117.198321   
16            1     0       17      117.194     39.1574      117.200318   
17            1     0       18      117.197     39.1593      117.203313   
18            1     0       19      117.200     39.1628      117.206309   
19            1     0       20      117.211     39.1650      117.217294   
20            1     0       21      117.214     39.1650      117.220291   
21            1     0       22      117.218     39.1653      117.224287   
22            1     0       23      117.220     39.1670      117.226285   
23            1     0       24      117.216     39.1699      117.222289   
24            1     0       25      117.218     39.1729      117.224287   
25            1     0       26      117.221     39.1743      117.227285   
26            1     0       27      117.225     39.1766      117.231282   
27            1     0       28      117.229     39.1774      117.235280   
28            1     0       29      117.231     39.1750      117.237279   
29            1     0       30      117.233     39.1729      117.239278   
...         ...   ...      ...          ...         ...             ...   
22343     61102     1       21      117.102     39.2688      117.108448   
22344     61102     1       22      117.104     39.2629      117.110448   
22345     61102     1       23      117.105     39.2587      117.111448   
22346     61102     1       24      117.108     39.2544      117.114448   
22347     61102     1       25      117.117     39.2340      117.123443   
22348     61102     1       26      117.119     39.2286      117.125442   
22349     61102     1       27      117.121     39.2240      117.127440   
22350     61102     1       28      117.128     39.2176      117.134434   
22351     61102     1       29      117.131     39.2140      117.137431   
22352     61102     1       30      117.134     39.2103      117.140427   
22353     61102     1       31      117.143     39.1995      117.149414   
22354     61102     1       32      117.150     39.1934      117.156402   
22355     61102     1       33      117.157     39.1881      117.163389   
22356     61102     1       34      117.160     39.1858      117.166384   
22357     61102     1       35      117.169     39.1818      117.175366   
22358     61102     1       36      117.174     39.1751      117.180356   
22359     61102     1       37      117.176     39.1714      117.182352   
22360     61102     1       38      117.178     39.1692      117.184348   
22361     61102     1       39      117.180     39.1651      117.186344   
22362     61102     1       40      117.184     39.1601      117.190336   
22363     61102     1       41      117.186     39.1576      117.192332   
22364     61102     1       42  

In [20]:
result=result.rename(columns={'longitude':'real_longitude','latitude':'real_latitude'})
result

O_LINENO  O_UP  STATION  O_LONGITUDE  O_LATITUDE  longitude_amap  \
0             1     0        1      117.198     39.1274      117.204307   
1             1     0        2      117.199     39.1258      117.205306   
2             1     0        3      117.195     39.1224      117.201312   
3             1     0        4      117.192     39.1207      117.198317   
4             1     0        5      117.187     39.1229      117.193325   
5             1     0        6      117.178     39.1252      117.184342   
6             1     0        7      117.179     39.1288      117.185341   
7             1     0        8      117.183     39.1293      117.189334   
8             1     0        9      117.186     39.1327      117.192329   
9             1     0       10      117.186     39.1347      117.192329   
10            1     0       11      117.181     39.1359      117.187338   
11            1     0       12      117.180     39.1394      117.186341   
12            1     0       13      117.180     39.1422      117.186341   
13            1     0       14      117.182     39.1431      117.188337   
14            1     0       15      117.189     39.1517      117.195326   
15            1     0       16      117.192     39.1555      117.198321   
16            1     0       17      117.194     39.1574      117.200318   
17            1     0       18      117.197     39.1593      117.203313   
18            1     0       19      117.200     39.1628      117.206309   
19            1     0       20      117.211     39.1650      117.217294   
20            1     0       21      117.214     39.1650      117.220291   
21            1     0       22      117.218     39.1653      117.224287   
22            1     0       23      117.220     39.1670      117.226285   
23            1     0       24      117.216     39.1699      117.222289   
24            1     0       25      117.218     39.1729      117.224287   
25            1     0       26      117.221     39.1743      117.227285   
26            1     0       27      117.225     39.1766      117.231282   
27            1     0       28      117.229     39.1774      117.235280   
28            1     0       29      117.231     39.1750      117.237279   
29            1     0       30      117.233     39.1729      117.239278   
...         ...   ...      ...          ...         ...             ...   
22343     61102     1       21      117.102     39.2688      117.108448   
22344     61102     1       22      117.104     39.2629      117.110448   
22345     61102     1       23      117.105     39.2587      117.111448   
22346     61102     1       24      117.108     39.2544      117.114448   
22347     61102     1       25      117.117     39.2340      117.123443   
22348     61102     1       26      117.119     39.2286      117.125442   
22349     61102     1       27      117.121     39.2240      117.127440   
22350     61102     1       28      117.128     39.2176      117.134434   
22351     61102     1       29      117.131     39.2140      117.137431   
22352     61102     1       30      117.134     39.2103      117.140427   
22353     61102     1       31      117.143     39.1995      117.149414   
22354     61102     1       32      117.150     39.1934      117.156402   
22355     61102     1       33      117.157     39.1881      117.163389   
22356     61102     1       34      117.160     39.1858      117.166384   
22357     61102     1       35      117.169     39.1818      117.175366   
22358     61102     1       36      117.174     39.1751      117.180356   
22359     61102     1       37      117.176     39.1714      117.182352   
22360     61102     1       38      117.178     39.1692      117.184348   
22361     61102     1       39      117.180     39.1651      117.186344   
22362     61102     1       40      117.184     39.1601      117.190336   
22363     61102     1       41      117.186     39.1576      117.192332   
22364     61102     1       42  

In [21]:
len(result.station_id.unique())

3456

In [22]:
result.to_csv('../bus_data/stationmap/match_result_merge_near.csv',index=False)