In [1]:
import pandas as pd
import numpy as np

In [2]:
df1 = pd.read_csv('../bus_data/stationmap/location_corrected.csv')
df1

station_id       name   longitude   latitude
0              0      247社区  117.337807  39.709927
1              1      奥克斯电气  117.010269  39.416382
2              2        奥兰里  117.252777  39.133121
3              3    奥林匹克博物馆  117.554939  38.927555
4              4       奥林花园  117.654144  39.044552
5              5        安乐村  117.362724  39.689865
6              6       安光小学  116.999702  39.217419
7              7        安光村  116.999611  39.223274
8              8      安光油墨厂  116.999649  39.221779
9              9        安太里  117.655975  39.017632
10            10        安定里  117.186646  39.165951
11            11        安泽里  117.136047  39.145187
12            12       安津医院  117.069290  39.233574
13            13       安裕新村  117.418961  40.039059
14            14        安达桥  117.424843  38.871178
15            15        安阳道  117.663864  38.993320
16            16         敖北  116.930908  39.308361
17            17       敖嘴村口  116.958267  39.312737
18            18         敖西  116.930908  39.308361
19            19       爱国东里  117.394356  38.670040
20            20       爱国北里  117.218575  39.098717
21            21        爱国里  117.220016  39.097752
22            22        爱营里  117.249550  39.146576
23            23        艾林庄  117.643242  39.455292
24            24        艾蒲庄  116.997688  39.319023
25            25       阿尔卑斯  117.235428  38.993500
26            26       鞍山西道  117.157745  39.113945
27            27        鞍山道  117.188660  39.120312
28            28      BBA公司  117.713768  39.051575
29            29       五号堤路  117.223724  39.074368
...          ...        ...         ...        ...
6029        6029        赵庄南  112.536469  37.922756
6030        6030        赵庄子  116.239403  40.060726
6031        6031       赵庄子村  116.832458  38.875572
6032        6032         赵本  117.652069  39.467297
6033        6033        赵沽里  117.249886  39.170387
6034        6034        赵温村  117.407166  39.253456
6035        6035      赵翰林庄村  117.248566  39.954449
6036        6036       赵苑小区  117.110329  39.153313
6037        6037        赵连庄  117.235802  38.794861
6038        6038     辰兴路佳宁道  117.132523  39.197834
6039        6039       造甲中学  117.454544  39.282444
6040        6040    造甲国道服务站  117.407872  39.292724
6041        6041      造甲工业区  117.437706  39.282700
6042        6042      造甲邮政所  117.451912  39.282478
6043        6043      造甲镇政府  117.431793  39.282909
6044        6044       造纸宿舍  117.310730  39.091541
6045        6045  造纸宿舍(张贵庄)  117.310730  39.091541
6046        6046        郑家套  117.402817  39.932892
6047        6047        郑家楼  116.887917  39.192200
6048        6048        郑州道  117.811913  38.999084
6049        6049        郑庄子  117.252625  39.091072
6050        6050   郑庄子[西青区]  116.984329  39.098854
6051        6051       郑庄子村  117.545265  39.002903
6052        6052         重工  117.728271  38.982819
6053        6053      重阳里南门  117.463348  38.844570
6054        6054       鑫银大厦  117.203323  39.096134
6055        6055       钻井公司  117.513802  38.691814
6056        6056        钻井路  117.693420  38.974426
6057        6057   镇政府[静海镇]  116.922920  38.929836
6058        6058        震新村  117.809563  39.278263

[6059 rows x 4 columns]

In [3]:
a_x = np.ones((len(df1),len(df1)))
ttt = np.array(df1.longitude)
a_x = ttt * a_x
a_x = a_x.T
a_x

array([[117.337807, 117.337807, 117.337807, ..., 117.337807, 117.337807,
        117.337807],
       [117.010269, 117.010269, 117.010269, ..., 117.010269, 117.010269,
        117.010269],
       [117.252777, 117.252777, 117.252777, ..., 117.252777, 117.252777,
        117.252777],
       ...,
       [117.69342 , 117.69342 , 117.69342 , ..., 117.69342 , 117.69342 ,
        117.69342 ],
       [116.92292 , 116.92292 , 116.92292 , ..., 116.92292 , 116.92292 ,
        116.92292 ],
       [117.809563, 117.809563, 117.809563, ..., 117.809563, 117.809563,
        117.809563]])

In [4]:
b_x = a_x.T
b_x

array([[117.337807, 117.010269, 117.252777, ..., 117.69342 , 116.92292 ,
        117.809563],
       [117.337807, 117.010269, 117.252777, ..., 117.69342 , 116.92292 ,
        117.809563],
       [117.337807, 117.010269, 117.252777, ..., 117.69342 , 116.92292 ,
        117.809563],
       ...,
       [117.337807, 117.010269, 117.252777, ..., 117.69342 , 116.92292 ,
        117.809563],
       [117.337807, 117.010269, 117.252777, ..., 117.69342 , 116.92292 ,
        117.809563],
       [117.337807, 117.010269, 117.252777, ..., 117.69342 , 116.92292 ,
        117.809563]])

In [5]:
a_y = np.ones((len(df1),len(df1)))
ttt = np.array(df1.latitude)
a_y = ttt * a_y
b_y = a_y
a_y = b_y.T
display(a_y,b_y)

array([[39.709927, 39.709927, 39.709927, ..., 39.709927, 39.709927,
        39.709927],
       [39.416382, 39.416382, 39.416382, ..., 39.416382, 39.416382,
        39.416382],
       [39.133121, 39.133121, 39.133121, ..., 39.133121, 39.133121,
        39.133121],
       ...,
       [38.974426, 38.974426, 38.974426, ..., 38.974426, 38.974426,
        38.974426],
       [38.929836, 38.929836, 38.929836, ..., 38.929836, 38.929836,
        38.929836],
       [39.278263, 39.278263, 39.278263, ..., 39.278263, 39.278263,
        39.278263]])

array([[39.709927, 39.416382, 39.133121, ..., 38.974426, 38.929836,
        39.278263],
       [39.709927, 39.416382, 39.133121, ..., 38.974426, 38.929836,
        39.278263],
       [39.709927, 39.416382, 39.133121, ..., 38.974426, 38.929836,
        39.278263],
       ...,
       [39.709927, 39.416382, 39.133121, ..., 38.974426, 38.929836,
        39.278263],
       [39.709927, 39.416382, 39.133121, ..., 38.974426, 38.929836,
        39.278263],
       [39.709927, 39.416382, 39.133121, ..., 38.974426, 38.929836,
        39.278263]])

In [6]:
distance = ((a_x - b_x)*1000)**2 + ((a_y - b_y)*1000)**2
distance

array([[     0.        , 193449.80846901, 339935.262536  , ...,
        667422.32676998, 780673.19105002, 408887.53243197],
       [193449.80846901,      0.        , 139046.92418501, ...,
        662020.39473699, 244356.857917  , 657947.75659698],
       [339935.262536  , 139046.92418501,      0.        , ...,
        219350.35647398, 150130.43167401, 331076.84995997],
       ...,
       [667422.32676998, 662020.39473699, 219350.35647398, ...,
             0.        , 595658.5181    , 105806.119018  ],
       [780673.19105002, 244356.857917  , 150130.43167401, ...,
        595658.5181    ,      0.        , 907537.18377799],
       [408887.53243197, 657947.75659698, 331076.84995997, ...,
        105806.119018  , 907537.18377799,      0.        ]])

In [29]:
np.where((distance[50,60:]<1000 ))

(array([995, 996, 997]),)

### *`distance`*取0.9~1左右为80米

In [8]:
df_temp = pd.DataFrame(columns=['station_id','name','longitude','latitude'])
df_temp

Empty DataFrame
Columns: [station_id, name, longitude, latitude]
Index: []

In [47]:
df2 = df_temp.copy()
appear = set()
a = 0
for i in range(distance.shape[0]):
#for i in range(1000):
    if i in appear:
        #print(i)
        continue
    else:
        appear.add(i)
        ttt = np.where(distance[i,i:] < 0.8)
        if len(ttt[0]) == 1:
            df2 = df2.append(df1.loc[i,:],ignore_index=True)
        else:
            temp = {}
            temp['station_id'] = i
            temp['name'] = '{}'.format(df1.loc[i,'name'])
            lon_temp = df1.loc[i,'longitude']
            lat_temp = df1.loc[i,'latitude']
            for j in range(1,len(ttt[0])):
                temp['name'] = temp['name'] + '/' + '{}'.format(df1.loc[ttt[0][j]+i,'name'])
                lon_temp += df1.loc[ttt[0][j]+i,'longitude']
                lat_temp += df1.loc[ttt[0][j]+i,'latitude']
                appear.add(ttt[0][j]+i)
            temp['longitude'] = lon_temp/(len(ttt[0]))
            temp['latitude'] = lat_temp/(len(ttt[0]))
            df2 = df2.append(temp,ignore_index=True)
            #print(temp)
            #print(i,ttt[0]+i)
            a += 1
print(a)
df2

18
58
73
74
103
104
138
141
153
156
170
207
222
229
235
239
240
243
250
253
257
272
273
274
303
316
325
328
339
364
368
375
379
381
395
405
413
416
418
421
428
457
478
482
508
522
531
536
553
565
574
576
581
594
597
601
631
633
655
667
680
682
686
701
706
723
742
751
791
807
819
839
850
859
861
881
902
911
912
925
927
950
952
957
961
983
996
1000
1001
1009
1029
1040
1051
1055
1072
1082
1093
1096
1101
1118
1125
1126
1134
1137
1154
1155
1168
1170
1190
1201
1219
1246
1255
1272
1285
1293
1332
1354
1366
1418
1422
1426
1438
1457
1464
1478
1480
1489
1498
1499
1504
1545
1552
1571
1576
1585
1604
1610
1612
1617
1618
1625
1626
1637
1653
1665
1672
1686
1697
1763
1773
1786
1799
1803
1824
1826
1838
1870
1887
1917
1930
1932
1937
1946
1950
1952
1964
1981
1999
2010
2023
2036
2048
2057
2062
2065
2071
2093
2119
2122
2137
2155
2163
2171
2182
2192
2199
2245
2249
2258
2266
2267
2270
2303
2326
2333
2352
2358
2377
2382
2404
2419
2428
2430
2438
2452
2464
2487
2489
2491
2495
2499
2511
2513
2520
2522
2528
2530
2

station_id            name   longitude   latitude
0             0           247社区  117.337807  39.709927
1             1           奥克斯电气  117.010269  39.416382
2             2             奥兰里  117.252777  39.133121
3             3         奥林匹克博物馆  117.554939  38.927555
4             4            奥林花园  117.654144  39.044552
5             5             安乐村  117.362724  39.689865
6             6            安光小学  116.999702  39.217419
7             7             安光村  116.999611  39.223274
8             8           安光油墨厂  116.999649  39.221779
9             9             安太里  117.655975  39.017632
10           10             安定里  117.186646  39.165951
11           11             安泽里  117.136047  39.145187
12           12            安津医院  117.069290  39.233574
13           13            安裕新村  117.418961  40.039059
14           14             安达桥  117.424843  38.871178
15           15             安阳道  117.663864  38.993320
16           16           敖北/敖西  116.930908  39.308361
17           17            敖嘴村口  116.958267  39.312737
18           19            爱国东里  117.394356  38.670040
19           20            爱国北里  117.218575  39.098717
20           21             爱国里  117.220016  39.097752
21           22             爱营里  117.249550  39.146576
22           23             艾林庄  117.643242  39.455292
23           24             艾蒲庄  116.997688  39.319023
24           25            阿尔卑斯  117.235428  38.993500
25           26            鞍山西道  117.157745  39.113945
26           27             鞍山道  117.188660  39.120312
27           28           BBA公司  117.713768  39.051575
28           29            五号堤路  117.223724  39.074368
29           30            保利天汇  117.812114  39.338536
...         ...             ...         ...        ...
5396       6027              赵庄  117.197662  39.258694
5397       6028            赵庄中学  117.804924  39.353687
5398       6029             赵庄南  112.536469  37.922756
5399       6030             赵庄子  116.239403  40.060726
5400       6031            赵庄子村  116.832458  38.875572
5401       6032              赵本  117.652069  39.467297
5402       6033             赵沽里  117.249886  39.170387
5403       6034             赵温村  117.407166  39.253456
5404       6035           赵翰林庄村  117.248566  39.954449
5405       6036            赵苑小区  117.110329  39.153313
5406       6037             赵连庄  117.235802  38.794861
5407       6038          辰兴路佳宁道  117.132523  39.197834
5408       6039            造甲中学  117.454544  39.282444
5409       6040         造甲国道服务站  117.407872  39.292724
5410       6041           造甲工业区  117.437706  39.282700
5411       6042           造甲邮政所  117.451912  39.282478
5412       6043           造甲镇政府  117.431793  39.282909
5413       6044  造纸宿舍/造纸宿舍(张贵庄)  117.310730  39.091541
5414       6046             郑家套  117.402817  39.932892
5415       6047             郑家楼  116.887917  39.192200
5416       6048             郑州道  117.811913  38.999084
5417       6049             郑庄子  117.252625  39.091072
5418       6050        郑庄子[西青区]  116.984329  39.098854
5419       6051            郑庄子村  117.545265  39.002903
5420       6052              重工  117.728271  38.982819
5421       6053           重阳里南门  117.463348  38.844570
5422       6054            鑫银大厦  117.203323  39.096134
5423       6055            钻井公司  117.513802  38.691814
5424       6057        镇政府[静海镇]  116.922920  38.929836
5425       6058             震新村  117.809563  39.278263

[5426 rows x 4 columns]

In [48]:
del df2['station_id']

In [49]:
df2.to_csv('../bus_data/stationmap/location_merge_near.csv',index_label='station_id')